= StringTemplate3
Fredrick eisele <https://github.com/phreed[@phreed]>
// settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Variables:
// URLs:
:url-org: https://github.com/phreed
:url-project: {url-org}/StringTemplate3
// images:

{url-project}[StringTemplate3] provides a python3 implementation of https://github.com/antlr/stringtemplate4

== StringTemplate3 

include::docs/description.rst[]

== Requirements

As this is a pure Python project it needs Python3.

== Building

The following mamba environment was used.

[source,shell]
----
mamba install -c conda-forge python-build
mamba install -c conda-forge twine
mamba install -c conda-forge pip
mamba install -c conda-forge pytest
----

=== Package managers

The two main package managers for Python are `pip` and `conda`.
(I use the mamba variant.)

==== Pip

* https://packaging.python.org/en/latest/tutorials/packaging-projects/
* https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

.build the package
* https://github.com/pypa/build
[source,shell]
----
python -m build --wheel
----

Before uploading anywhere the wheel file can be installed.
.install the wheel locally
[source,shell]
----
python -m pip install ./dist/stringtemplate3x-*-py3-*.whl
----

Before uploading to the official site upload to the test repository.

.testing the package
* https://test.pypi.org/help/#apitoken

[source,shell]
----
python -m twine upload --repository testpypi dist/*
----

Publishing to the official repository.

.publish the package
* https://pypi.org/help/#apitoken

[source,shell]
----
python -m twine upload --repository pypi dist/*
----

===== Install

.install from testpypi https://test.pypi.org/project/stringtemplate3x/
[source,shell]
----
python -m pip install -i https://test.pypi.org/simple/ stringtemplate3x
----

.install from pypi https://pypi.org/project/stringtemplate3x/
[source,shell]
----
python -m pip install stringtemplate3x
----

==== Conda

Note: handled in a separate project.
Not yet implemented.

===== Install

.install from conda-forge https://anaconda.org/conda-forge/stringtemplate3
[source,shell]
----
mamba install stringtemplate3
----

== Usage
This will be handled via conda-forge which requires a separate feedstock project.




== Contributing

New contributors are always welcome!
If you discover errors or omissions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix.

== Getting Help

== Changelog

ifeval::[{safe-mode-level} < 20]
include::docs/change_log.adoc[tag=compact,leveloffset=+1]
endif::[]
