= StringTemplate3
Fredrick eisele <https://github.com/phreed[@phreed]>
// settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Variables:
// URLs:
:url-org: https://github.com/phreed
:url-project: {url-org}/StringTemplate3
// images:

{url-project}[StringTemplate3] provides a python3 implementation of https://github.com/antlr/stringtemplate4

== StringTemplate3

include::docs/description.txt[]

== Requirements

As this is a pure Python project it needs Python3.

== Building

The following mamba environment was used.

[source,shell]
----
mamba install -c conda-forge python-build
mamba install -c conda-forge twine
mamba install -c conda-forge pip
mamba install -c conda-forge pytest
----

=== Package managers

The two main package managers for Python are `pip` and `conda`.
(I use the mamba variant.)

==== Pip

* https://packaging.python.org/en/latest/tutorials/packaging-projects/

.testing the package
* https://test.pypi.org/help/#apitoken

[source,shell]
----
python -m build --wheel src
----

[source,shell]
----
python -m twine upload --repository pypi dist/*
----

==== Conda


== Contributing

Contributors are welcome but this is largely a discontinued project.
It provides a path for the discontinued `stringtemplate3` python port.
It should be used as a last resort.
The `stringtemplate4` project should be preferred.
That being said, if you discover errors or omissions in the source code,
documentation, or website content,
please do not hesitate to submit an issue or open a pull request with a fix.

== Changelog

ifeval::[{safe-mode-level} < 20]
include::docs/change_log.adoc[tag=compact,leveloffset=+1]
endif::[]
